@startuml
left to right direction

actor Администратор
actor Тренер
actor Клиент

usecase "Управление инвентарем" as UC1
usecase "Управление пользователями" as UC2
usecase "Просмотр отчетов" as UC3
usecase "Бронирование инвентаря" as UC4
usecase "Просмотр доступного инвентаря" as UC5
usecase "История использования" as UC6
usecase "Отметка о возврате" as UC7

Администратор --> UC1
Администратор --> UC2
Администратор --> UC3
Администратор --> UC7

Тренер --> UC4
Тренер --> UC5
Тренер --> UC6
Тренер --> UC7

Клиент --> UC4
Клиент --> UC5
Клиент --> UC6

@enduml