@startuml
start
:Клиент возвращает инвентарь;
:Проверить состояние;

if (Исправен?) then (Да)
  :Обновить статус: Доступен;
else (Нет)
  :Зафиксировать повреждение;
  :Перевести в статус: Нужен ремонт;
  :Уведомить администратора;
endif

:Записать в историю возврата;
stop
@enduml