@startuml
start
:Запрос на выдачу инвентаря;
if (Проверить доступность) then (Доступен)
  if (Проверить статус клиента) then (Активен)
    :Забронировать инвентарь;
    :Обновить статус: "Выдан";
    :Записать в историю;
    :Выдать инвентарь клиенту;
  else (Не активен)
    :Отказать в выдаче;
  endif
else (Не доступен)
  :Уведомить о недоступности;
endif
:Конец процесса;
stop
@enduml